#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10

#define NUM_ALTERING_CAVE_TABLES 9

#define HEADER_NONE 0xFFFF

#define WILD_AREA_LAND      0
#define WILD_AREA_WATER     1
#define WILD_AREA_ROCKS     2
#define WILD_AREA_FISHING   3

#define WILD_CHECK_REPEL    (1 << 0)
#define WILD_CHECK_KEEN_EYE (1 << 1)

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
